### ISSUE TITLE
[BUG] Audio calibration "Tap Me" button activates when released rather than when pressed

### ISSUE THREAD

**Issue by jummy0** [MatteoGodzilla/Dj-Engine#11]
**Describe the bug**

**To Reproduce**
1. Go to Options
2. Go to Calibrate Latency
3. Click Calibrate
4. Click the Tap Me button, holding down the button a bit after each click. The calibration will be aligned to the end of each click rather than the start, making the result inaccurate.

**Expected behavior**
The calibration would be aligned to the start of the click.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by MatteoGodzilla** [comment]
fixed with commit abff41844ecb02d76a07eed44764fbde0ff57346
