### ISSUE TITLE
[BUG] Side-to-side crossfades break combo unless the player pass through the middle

### ISSUE THREAD

**Issue by jummy0** [MatteoGodzilla/Dj-Engine#13]
**Describe the bug**
When playing a side-to-side crossfade (left -> right;  right -> left), the combo will be dropped unless the player passes through the center on the way to the opposite side. For controller this isn't much of an issue, but for keyboard it's very noticeable.

**To Reproduce**
1. Play a song with a side-to-side crossfade.
2. Go directly from holding Crossfade Left to holding Crossfade Right without letting go.
3. Combo is broken.

**Expected behavior**
Combo should continue even if the player doesn't pass through the center crossfade state.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1903

**Comment by jummy0** [comment]
Still relevant in version 1.4.

**Comment by MatteoGodzilla** [comment]
fixed with commit a544806ffaac22fb4183fdbc285889b6f667c8c1
