### ISSUE TITLE
[BUG] Game opens but crashes on selection

### ISSUE THREAD

**Issue by ghost** [MatteoGodzilla/Dj-Engine#15]
**Describe the bug**
I click to open the game, and so far fine and dandy everything works, but when i click play or options to go to the song selection menu, or the options menu the game crahses. i have installed openAL as it said i needed it, but i dont think openAL would be the problem.

**To Reproduce**
1. click and open game
2. scroll to either play or options and press space to select
3. game crashes

**Expected behavior**
I kind of at least expected to get to options menu to check out the default options to see if any needed to be changed for my system

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate
 - Version ??

**Additional context**
Just found out both the credits and exit buttons also crash the game.
also checked task manager and the game uses about the same amount of ram and cpu usage as clone hero does, so i dont see why it would be crashing.

**Comment by MatteoGodzilla** [comment]
Please provide with more details.
If you can upload a video with both the game and console visible and link it.
I cannot understand the type of crash from the description
