### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tommozzarello** [MatteoGodzilla/Dj-Engine#20]
**Describe the bug**
I run game,later window with error.(Sorry,i know english bad,im from Russia)

**To Reproduce**
1. Go to 'C:\Program Files (x86)\MatteoGodzilla\Dj-Engine'
2. Click on 'Dj-Engine.exe'
3. See error

**Expected behavior**

I don't know what to write here

**Screenshots**
![error](https://user-images.githubusercontent.com/62063919/76423711-0152c780-63c9-11ea-87fb-2230ab4c6b16.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 7 Home Premium 
 - Version 6.1.7601 Service Pack 1 build 7601

**Additional context**
I trying run with administrator rights

**Comment by MatteoGodzilla** [comment]
Sorry for the late reply.
That looks like an error with Visual C++ redist. 
Try reinstalling it from the link below and then run dje again:
https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by tommozzarello** [comment]
Same error
