### ISSUE TITLE
[BUG] crossfader is inverted

### ISSUE THREAD

**Issue by iamjen023** [MatteoGodzilla/Dj-Engine#22]
when i move the crossfader ingame if i go right ingame it goes left
if i go left it goes right 
i dont see a way to invert it in remapping
im useing a dj hero xbox 360 with wireless dongle

**Comment by MatteoGodzilla** [comment]
sorry for the late reply
in general putting a negative value in the sensitivity flips the axis direction, so you can put a -1 on the crossfade entry and it will solve that problem

I already know this problem and this happenes because the crossfade is wired the opposite way on the turntable itself.
