### ISSUE TITLE
[BUG] game doesn't create config.ini if missing

### ISSUE THREAD

**Issue by jummy0** [MatteoGodzilla/Dj-Engine#24]
**Describe the bug**
If a config file is missing, the game does not replace it and treats all values as 0 (lane colors are set to transparent, etc.)

**To Reproduce**
- Delete config.ini
- Start the game
- Console spits out errors

**Expected behavior**
The config file should be regenerated with default values.

**Desktop (please complete the following information):**
 - OS: Windows 10 v1903

**Comment by MatteoGodzilla** [comment]
fixed with commit a544806ffaac22fb4183fdbc285889b6f667c8c1
