### ISSUE TITLE
[BUG] tap notes z-order is backwards

### ISSUE THREAD

**Issue by jummy0** [MatteoGodzilla/Dj-Engine#25]
**Describe the bug**
If tap notes are close enough to overlap, further taps will show in _front_ of nearer taps.
![The bug in _Bounce vs. Say Woah_ on notespeed 2.0](https://user-images.githubusercontent.com/4022196/83341486-b353ae80-a2a9-11ea-8d7c-d9568a9abc16.png)

**To Reproduce**
1. Play a song with multiple taps in quick succession (or decrease the notespeed).

**Expected behavior**
Nearer taps should be drawn in front of farther taps.

**Comment by aleb2000** [comment]
I don't have a suitable chart to test if the fix actually works but it should be pretty straightforward, @MatteoGodzilla can you take a look (or if anyone can pass me a chart I will test it myself)? I created a new branch as I didn't want to unsync you with the remote.

**Comment by MatteoGodzilla** [comment]
fixed with commit a544806ffaac22fb4183fdbc285889b6f667c8c1
