### ISSUE TITLE
[BUG] can't use menu buttons to exit results screen

### ISSUE THREAD

**Issue by jummy0** [MatteoGodzilla/Dj-Engine#26]
**Describe the bug**
The song results screen requires the player to press Green rather than the menu buttons, contradicting the idea of "menu buttons"

**To Reproduce**
1. Complete a song
2. Press Start or Back

**Expected behavior**
The screen should be dismissed.

**Comment by MatteoGodzilla** [comment]
fixed with commit 0bf77643ef1ce9f1464f8fb11461a0e38d10b5eb
