### ISSUE TITLE
[BUG] "Set Deck Speed:1.000000" is never updated with the correct number

### ISSUE THREAD

**Issue by jummy0** [MatteoGodzilla/Dj-Engine#27]
**Describe the bug**
in the options menu, the "Set Deck Speed:1.000000" text is never updated when the deckspeed is updated.  however, the speed takes effect in game.

**To Reproduce**
1. Go to Options
2. Change deck speed

**Expected behavior**
The displayed number should match the selected deckspeed

**Comment by MatteoGodzilla** [comment]
fixed with commit a544806ffaac22fb4183fdbc285889b6f667c8c1
