### ISSUE TITLE
[BUG] moving or resizing the window during a song can stop music playback

### ISSUE THREAD

**Issue by jummy0** [MatteoGodzilla/Dj-Engine#29]
**Describe the bug**
While playing a song, if you drag the window around for more than a half-second or so, the song will mute and not return until playing a new chart. The gameplay seems to continue as normal.

**To Reproduce**
1. Start a song.
2. Drag the window around for a couple seconds.
3. Music playback stops while the chart continues,

**Desktop (please complete the following information):**
 - OS: Windows 10 v1903

**Comment by MatteoGodzilla** [comment]
fixed with commit a544806ffaac22fb4183fdbc285889b6f667c8c1
