### ISSUE TITLE
[BUG] results screen does not report full combo if the combo is less than the note count

### ISSUE THREAD

**Issue by jummy0** [MatteoGodzilla/Dj-Engine#30]
**Describe the bug**
If the combo of a song is a lower number than the note count (i.e., there are any simultaneous hits), the results screen will not report a full combo.

**To Reproduce**
1. Play a song with simultaneous hits (the DJH2 tutorials are easy choices)
2. Get a full combo
3. The results screen does not congratulate you.

**Expected behavior**
The results screen should report a full combo even if the combo is less than the note count.

**Screenshots**
![image](https://user-images.githubusercontent.com/4022196/83357486-3ddff080-a332-11ea-908a-504b8b21ec87.png)

**Comment by MatteoGodzilla** [comment]
changed the full combo logic on commit a544806ffaac22fb4183fdbc285889b6f667c8c1
