### ISSUE TITLE
[BUG] Build fails with unusual error: 'float.h' file not found 

### ISSUE THREAD

**Issue by shockdude** [MatteoGodzilla/Dj-Engine#31]
**Describe the bug**
During ./build.sh, when Dj-Engine.cpp.o is being built, the build fails and outputs an unusual error involving 'float.h'

```
C:\msys64\mingw64\x86_64-w64-mingw32\include\float.h:28:15: error: 'float.h' file not found [clang-diagnostic-error]
#include_next <float.h>
```

**To Reproduce**
1. Install msys2-x86_64-20200522.exe (https://github.com/msys2/msys2-installer/releases)
2. Follow installation & update instructions as described at https://www.msys2.org/
3. Install dependencies as described in compile.md, plus:
a. `mingw-w64-x86_64-clang-tools-extra`
b. `mingw-w64-x86_64-z3`
4. Run ./init.sh
5. Run ./build.sh

**Expected behavior**
Game builds successfully.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 1909

**Additional context**
Build output: [log.txt](https://github.com/MatteoGodzilla/Dj-Engine/files/4708527/log.txt)
List of installed packages: [packages.txt](https://github.com/MatteoGodzilla/Dj-Engine/files/4708526/packages.txt)

**Comment by MatteoGodzilla** [comment]
should be fixed with commit a544806ffaac22fb4183fdbc285889b6f667c8c1
