### ISSUE TITLE
Scratch zones can be played without starting a new button press

### ISSUE THREAD

**Issue by jummy0** [MatteoGodzilla/Dj-Engine#35]
In both DJ Hero games, the player needs to press green/blue to "enter" a scratch zone before any scratches can be hit.

This is missing from Dj-Engine, which makes some charts easier than they should be. The player can hold the green/blue button through multiple scratch zones without letting go, which shouldn't be possible.

Have not tested on v1.5.

**Comment by MatteoGodzilla** [comment]
I remember adding the required press in v1.5.
